# Generated by Django 4.2.7 on 2023-11-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMammaMia', '0003_alter_ingrediente_imagen_alter_masa_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='pizzas',
            field=models.ManyToManyField(related_name='ingredientes_rel', to='appMammaMia.pizza'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='ingredientes',
            field=models.ManyToManyField(to='appMammaMia.ingrediente'),
        ),
    ]
