# Generated by Django 4.2.7 on 2023-11-30 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMammaMia', '0004_ingrediente_pizzas_alter_pizza_ingredientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='pizzas',
        ),
    ]
