# Generated by Django 4.2.7 on 2023-12-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMammaMia', '0008_alter_ingrediente_imagen_datoscliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoscliente',
            name='comentario',
            field=models.TextField(null=True),
        ),
    ]
