# Generated by Django 4.2.7 on 2023-12-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMammaMia', '0009_datoscliente_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoscliente',
            name='comentario',
            field=models.TextField(),
        ),
    ]
