# Generated by Django 4.2.7 on 2023-12-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMammaMia', '0010_alter_datoscliente_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoscliente',
            name='telefono',
            field=models.IntegerField(default=21, max_length=9),
        ),
    ]
