# Generated by Django 4.2.7 on 2023-12-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMammaMia', '0011_datoscliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoscliente',
            name='telefono',
            field=models.IntegerField(max_length=9),
        ),
    ]
