# Generated by Django 4.2.7 on 2023-12-03 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMammaMia', '0013_remove_datoscliente_pedido_pedido_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datoscliente',
            name='comentario',
        ),
        migrations.AddField(
            model_name='pedido',
            name='comentario',
            field=models.TextField(default='hoal'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMammaMia.datoscliente'),
        ),
    ]
