# Generated by Django 4.2.7 on 2023-12-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMammaMia', '0014_remove_datoscliente_comentario_pedido_comentario_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Masa',
            new_name='Masas',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='comentario',
            field=models.TextField(),
        ),
    ]
