# Generated by Django 4.2.7 on 2023-12-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMammaMia', '0015_rename_masa_masas_alter_pedido_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pizzaATuGusto',
            field=models.ManyToManyField(blank=True, null=True, to='appMammaMia.pizzaatugusto'),
        ),
        migrations.AlterField(
            model_name='pizzaatugusto',
            name='ingrediente',
            field=models.ManyToManyField(blank=True, null=True, to='appMammaMia.ingrediente'),
        ),
    ]
