# Generated by Django 4.2.7 on 2023-12-04 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMammaMia', '0016_alter_pedido_pizzaatugusto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaatugusto',
            name='masa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appMammaMia.masas'),
        ),
    ]
