# Generated by Django 4.2.7 on 2023-12-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMammaMia', '0017_alter_pizzaatugusto_masa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebida',
            name='imagen',
            field=models.ImageField(upload_to='bebidas/'),
        ),
        migrations.AlterField(
            model_name='entrante',
            name='imagen',
            field=models.ImageField(upload_to='entrantes/'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='imagen',
            field=models.ImageField(upload_to='pizzas/'),
        ),
    ]
