# Generated by Django 5.0 on 2023-12-05 15:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMammaMia', '0018_alter_bebida_imagen_alter_entrante_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='comensales',
            field=models.IntegerField(default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_y_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reserva',
            name='mesas',
            field=models.IntegerField(default=1, max_length=2),
        ),
    ]
