# Generated by Django 4.2.7 on 2023-12-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMammaMia', '0019_reserva_comensales_reserva_fecha_y_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebida',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
    ]
