# Generated by Django 4.2.7 on 2023-12-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMammaMia', '0021_remove_bebida_descripcion_alter_ingrediente_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
    ]
