# Generated by Django 4.2.7 on 2023-12-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMammaMia', '0022_alter_pizza_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrante',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
    ]
