# Generated by Django 5.0 on 2023-12-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMammaMia', '0023_alter_entrante_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='mesas',
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_reserva',
            field=models.CharField(choices=[('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00')], default='13:00', max_length=5),
        ),
        migrations.AddField(
            model_name='reserva',
            name='mesas_asignadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reserva',
            name='mesas_disponibles',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='comensales',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1),
        ),
    ]
