# Generated by Django 4.2.7 on 2023-12-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMammaMia', '0025_remove_reserva_fecha_y_hora_reserva_fecha_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='precioTotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
